from oConsole import oConsole;
from mColors import *;

def fPrintHelp():
  oConsole.fPrint(HILITE, "Usage:");
  oConsole.fPrint("  ", INFO, "FileSystemBrowser", NORMAL, " [", INFO, "\"path to browse\"", NORMAL, "] [", INFO, "<options>", NORMAL, "]");
  oConsole.fPrint();
  oConsole.fPrint(HILITE, "Arguments:");
  oConsole.fPrint(INFO, "  \"path to browser\"");
  oConsole.fPrint("      Path to use as the root node (default = current working directory");
  oConsole.fPrint();
  oConsole.fPrint(HILITE, "Options:");
  oConsole.fPrint(INFO, "  --offline=\"path\"");
  oConsole.fPrint("    Do not start a webserver to allow browsing but instead create files for");
  oConsole.fPrint("    offline browsing or uploading to server.");
  oConsole.fPrint(INFO, "  --apply-sharepoint-hacks");
  oConsole.fPrint("    Modify offline files for use on SharePoint server where .json files are not");
  oConsole.fPrint("    allowed.");
  oConsole.fPrint(INFO, "  --http-direct");
  oConsole.fPrint("    Make direct requests to look up favicons for website links.");
  oConsole.fPrint(INFO, "  --http-proxy=hostname:port");
  oConsole.fPrint("    Use the specified hostname and port as a HTTP proxy to make requests to");
  oConsole.fPrint("    look up favicons for website links.");
  oConsole.fPrint(INFO, "  --http-timeout=<seconds>");
  oConsole.fPrint("    Wait for a HTTP response from a server or proxy for at most the given number");
  oConsole.fPrint("    of seconds before failing the request.");
  oConsole.fPrint("");
  oConsole.fPrint(HILITE, "Notes:");
  oConsole.fPrint("  You can provide the ", INFO, "--http-direct", NORMAL, " and/or ", INFO, "--http-proxy", NORMAL, " arguments to allow");
  oConsole.fPrint("  FileSystemBrowser to request any webpages that are linked to in order to");
  oConsole.fPrint("  determine their 'favicon' icon and use that for the link. Note that this can");
  oConsole.fPrint("  slow down the creation of the tree significantly.");
  oConsole.fPrint("  You can combine the ", INFO, "--http-direct", NORMAL, " and ", INFO, "--http-proxy", NORMAL, " arguments to try both");
  oConsole.fPrint("  direct requests and requests through a proxy when on an intranet. You can");
  oConsole.fPrint("  also specify multiple ", INFO, "--http-proxy", NORMAL, " arguments to have this");
  oConsole.fPrint("  script to try multiple proxies for each webpage untill the webpage can");
  oConsole.fPrint("  successfully be downloaded.");
  oConsole.fPrint("  If you provide the ", INFO, "--http-timeout", NORMAL, " argument, it will affect only");
  oConsole.fPrint("  connections made by the client based on ", INFO, "--http-direct", NORMAL, " and/or ", INFO, "--http-proxy");
  oConsole.fPrint("  arguments that come after it. This allows you to set different timeouts for");
  oConsole.fPrint("  these arguments.");
  oConsole.fPrint("  The order in which you provide the ", INFO, "--http-direct", NORMAL, " and ", INFO, "--http-proxy", NORMAL, " arguments");
  oConsole.fPrint("  determines the order in which request for webpages are attempted directly or");
  oConsole.fPrint("  through proxies.");
